### ISSUE TITLE
Installing on Arch Linux - no ELM_HOME?

### ISSUE THREAD

**Issue by CaptainLexington** [kevva/elm-bin#7]
Installing this package on Arch Linux leaves me with no ELM_HOME environment variable. I was told this file (https://github.com/elm-lang/elm-platform/blob/master/installers/windows/inst.dat#L8-L24) tells me where ELM_HOME should point but none of the files there indicated are on my system. Have I missed a step?

**Comment by kevva** [comment]
This is not a installer, it only provides the binaries and doesn't set any environment variables. Also, it doesnt support Windows.

**Comment by jvoigtlaender** [comment]
@kevva, would you be willing to merge a pull request that adds the static files required for the debugger mode of `elm-reactor`? They are OS independent. People would still need to set the ELM_HOME environment variable by hand using whatever means their OS has for that. But at least they would have all necessary files on their machine after just `npm install elm`.

(This would also simplify things like building docker containers with a ready-to-go, and debugger-enabled, Elm installation, because no extra files would need to be fetched -- everything would be already included via the `npm install` command.)

**Comment by passy** [comment]
@jvoigtlaender I think that's a good idea. :+1:

**Comment by jvoigtlaender** [comment]
Still wondering: @kevva, would you accept a pull request as mentioned above (providing the static files required for the debugger mode of `elm-reactor`)?

**Comment by kevva** [comment]
@jvoigtlaender, yes, of course :).

**Comment by jvoigtlaender** [comment]
Done: https://github.com/kevva/elm-bin/pull/15.

**Comment by CaptainLexington** [comment]
Thanks so much!
